require("configuration")

require("prototypes.assemblers")
require("prototypes.oil_refineries")
require("prototypes.chemical_plants")
require("prototypes.electric_mining_drills")
require("prototypes.pumpjacks")
require("prototypes.centrifuge")
require("prototypes.labs")
require("prototypes.electric_furnaces")
